// Code generated by hertz generator.

package record

import (
	"context"
	"github.com/jhue/misgo/biz/model/base"
	"github.com/jhue/misgo/biz/request"
	"github.com/jhue/misgo/db"
	recordM "github.com/jhue/misgo/db/model/record"
	"github.com/jhue/misgo/db/model/user"
	"github.com/jhue/misgo/internal/mislog"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/jhue/misgo/biz/model/record"
)

// Record .
// @router /record [PUT]
func Record(ctx context.Context, c *app.RequestContext) {
	biz := request.NewBizContext(c)
	var err error
	var req record.RecordReq
	err = c.BindAndValidate(&req)
	if err != nil {
		biz.ParmaError(err)
		return
	}
	u, ok := user.ExtractUser(ctx)
	if !ok {
		biz.ParmaError(base.UIDError)
		return
	}
	if req.Tag == "" || req.Content == "" {
		biz.ParmaError(record.TagContentEmptyError)
		return
	}

	d := db.Get()
	res := d.Create(&recordM.Record{
		UserID:  u.ID,
		Tag:     req.Tag,
		Content: req.Content,
		Extend:  req.Extend,
		Time:    time.Now(),
	})

	if res.Error != nil {
		biz.DBError(res.Error)
		return
	}
	biz.Success()
	mislog.DefaultLogger.Infof("Record Success [Name] %s [Tag] %s [Content] %s\n", u.Name, req.Tag, req.Content)
}
