clipBoardConfig:
  maxStore: 2
  fileStorePath: ./files/clipboard
  maxFileSizeMb: 10

recordConfig:
  maxGetCount: 2

moneyConfig:
  maxGetCount: 10
  parserConfig:
    separators: [",", "，", "。","；",";", "\n"]
    expenseKeywords: ["用了", "花了", "支出","开销","花费"]
    incomeKeywords: ["收入", "得到","获得"]