// Code generated by hertz generator.

package main

import (
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/jhue/misgo/biz/middleware"
	"github.com/jhue/misgo/internal/conf"
	"github.com/jhue/misgo/internal/mislog"
)

func main() {
	initPkg()
	config := conf.GetConfig()

	f, err := mislog.LogFileIO(config.LogPath)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	mislog.InitLogger(f, config.LogConfig)
	mislog.DefaultLogger.Infof("misgo version: %s", config.Version)
	h := server.Default(server.WithHostPorts(fmt.Sprintf("%s:%d", config.Host, config.Port)))
	h.Use(middleware.UIDExtractMiddleware())
	register(h)
	h.Spin()
}

func initPkg() {
	err := conf.InitConfig(Version)
	if err != nil {
		panic(err)
	}

}
