// Code generated by hertz generator.

package ping

import (
	"context"
	"fmt"
	"github.com/jhue/misgo/biz/request"
	"github.com/jhue/misgo/internal/conf"
	"github.com/jhue/misgo/internal/mislog"
	"time"

	"github.com/cloudwego/hertz/pkg/app"

	"github.com/jhue/misgo/biz/model/ping"
)

// Ping .
// @router /ping [GET]

func Ping(ctx context.Context, c *app.RequestContext) {
	config := conf.GetConfig()
	biz := request.NewBizContext(c)
	resp := &ping.PingResp{
		Message: fmt.Sprintf("pong from misgo%s", config.Version),
		Date:    time.Now().String(),
	}
	biz.Response(resp)
	mislog.DefaultLogger.Info("Ping")
}
