// Code generated by hertz generator.

package debug

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/jhue/misgo/biz"
	"github.com/jhue/misgo/biz/middleware"
	"github.com/jhue/misgo/biz/request"
	"github.com/jhue/misgo/internal/conf"
	"github.com/jhue/misgo/internal/mislog"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
)

// Debug .
// @router api/debug [GET]
func Debug(ctx context.Context, c *app.RequestContext) {
	bizCtx := request.NewBizContext(c)
	var err error

	sp, err := mislog.DefaultLogger.Snapshot()
	if err != nil {
		bizCtx.ServerError(err)
		return
	}

	sysConfig := conf.GetConfig()
	bizConfig := biz.GetBizConfig()

	// 格式化 sysConfig 为带缩进的 JSON 文本
	sysConfigJSON, err := json.MarshalIndent(sysConfig, "", "    ")
	if err != nil {
		bizCtx.ServerError(err)
	}

	// 格式化 bizConfig 为带缩进的 JSON 文本
	bizConfigJSON, err := json.MarshalIndent(bizConfig, "", "    ")
	if err != nil {
		bizCtx.ServerError(err)
	}

	var pprofString string
	v := ctx.Value(middleware.PprofKey{})
	p, ok := v.(*middleware.Pprof)
	if ok {
		pprofString = p.Report()

	}

	if pprofString == "" {
		pprofString = "无法获取Pprof信息"
	}

	output := fmt.Sprintf(
		"Server时钟:\n%s\n\n日志信息(后%d行):\n%s\n\nSysConfig:\n%s\n\nBizConfig:\n%s\n\n性能分析:\n%s",
		time.Now().String(),
		sysConfig.SnapshotLineCount,
		sp,
		sysConfigJSON,
		bizConfigJSON,
		pprofString,
	)

	bizCtx.Text(output)
}
