// Code generated by hertz generator.

package money

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _transactionputMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _transactiongetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _moneyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _transactiongetviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _transactiondeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _money0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _transactionputcontentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _transactioncontentMw() []app.HandlerFunc {
	// your code...
	return nil
}
