// Code generated by hertz generator.

package money

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _transactionputMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _transactiongetMw() []app.HandlerFunc {
	// your code...
	return nil
}
