// Code generated by hertz generator.

package debug

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _debugMw() []app.HandlerFunc {
	// your code...
	return nil
}
