// Code generated by hertz generator.

package user

import (
	"context"
	"github.com/jhue/misgo/biz/model/base"
	"github.com/jhue/misgo/biz/request"
	userM "github.com/jhue/misgo/db/model/user"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	user "github.com/jhue/misgo/biz/model/user"
)

// UserGet .
// @router api/user [GET]
func UserGet(ctx context.Context, c *app.RequestContext) {
	bizCtx := request.NewBizContext(c)
	var err error
	var req user.UserGetReq
	err = c.BindAndValidate(&req)
	if err != nil {
		bizCtx.ParmaError(err)
		return
	}

	u, ok := userM.ExtractUser(ctx)
	if !ok {
		bizCtx.ParmaError(base.UIDError)
		return
	}

	resp := user.UserInfo{
		UID:  u.UID,
		Name: u.Name,
	}

	c.JSON(consts.StatusOK, &resp)
}
