// Code generated by hertz generator.

package clipboard

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clipboardgetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clipboardputMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clipboardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clipboardfilegetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clipboardfileputMw() []app.HandlerFunc {
	// your code...
	return nil
}
