// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	errors "github.com/jhue/misgo/biz/router/errors"
	ping "github.com/jhue/misgo/biz/router/ping"
	record "github.com/jhue/misgo/biz/router/record"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!

	errors.Register(r)

	record.Register(r)

	ping.Register(r)

}
