// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	clipboard "github.com/jhue/misgo/biz/router/clipboard"
	errors "github.com/jhue/misgo/biz/router/errors"
	money "github.com/jhue/misgo/biz/router/money"
	ping "github.com/jhue/misgo/biz/router/ping"
	record "github.com/jhue/misgo/biz/router/record"
	user "github.com/jhue/misgo/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!

	user.Register(r)

	money.Register(r)

	clipboard.Register(r)

	errors.Register(r)

	record.Register(r)

	ping.Register(r)

}
